project_name: kubepug
version: 2

env:
  - COSIGN_YES=true

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

builds:
  - id: kubepug
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
    flags:
      - -trimpath
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: .
    binary: kubepug

signs:
  - id: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args:
      [
        "sign-blob",
        "--output-signature",
        "${artifact}.sig",
        "--output-certificate",
        "${artifact}.pem",
        "${artifact}",
      ]
    artifacts: checksum
  - id: packages
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args:
      [
        "sign-blob",
        "--output-signature",
        "${artifact}.sig",
        "--output-certificate",
        "${artifact}.pem",
        "${artifact}",
      ]
    artifacts: archive

archives:
  - id: kubepug
    builds:
      - kubepug
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github-native

release:
  github:
    owner: kubepug
    name: kubepug
